export const runtimeSceneBossDrawMethods = {
  drawNecromancer(enemy, screenX, screenY) {
    const ctx = this.ctx;
    const half = enemy.size / 2;
    const pulse = Math.sin((enemy.hpBarTimer || 0) * 0.06) * 0.5 + 0.5;
    ctx.fillStyle = "rgba(0, 0, 0, 0.42)";
    ctx.beginPath();
    ctx.ellipse(screenX, screenY + half * 0.82, half * 1.05, half * 0.42, 0, 0, Math.PI * 2);
    ctx.fill();
    const glow = ctx.createRadialGradient(screenX, screenY - half * 0.25, 2, screenX, screenY - half * 0.25, half * 1.5);
    glow.addColorStop(0, `rgba(180, 108, 255, ${0.18 + pulse * 0.18})`);
    glow.addColorStop(1, "rgba(50, 18, 70, 0)");
    ctx.fillStyle = glow;
    ctx.beginPath();
    ctx.arc(screenX, screenY - half * 0.2, half * 1.45, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = "#2e213f";
    ctx.beginPath();
    ctx.moveTo(screenX, screenY - half * 0.95);
    ctx.lineTo(screenX + half * 0.82, screenY - half * 0.15);
    ctx.lineTo(screenX + half * 0.46, screenY + half * 0.9);
    ctx.lineTo(screenX - half * 0.46, screenY + half * 0.9);
    ctx.lineTo(screenX - half * 0.82, screenY - half * 0.15);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = "#5d3e83";
    ctx.fillRect(screenX - half * 0.34, screenY - half * 0.24, half * 0.68, half * 0.95);
    ctx.fillStyle = "#e7def7";
    ctx.beginPath();
    ctx.arc(screenX, screenY - half * 0.36, half * 0.34, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = "#7d58a6";
    ctx.fillRect(screenX - half * 0.72, screenY - half * 0.08, half * 1.44, half * 0.14);
    ctx.fillStyle = "#ff7676";
    ctx.fillRect(screenX - 5, screenY - half * 0.42, 3, 2);
    ctx.fillRect(screenX + 2, screenY - half * 0.42, 3, 2);
    ctx.strokeStyle = "#b98fff";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(screenX + half * 0.82, screenY - half * 0.55);
    ctx.lineTo(screenX + half * 1.18, screenY + half * 0.8);
    ctx.stroke();
    ctx.fillStyle = "#d8caff";
    ctx.beginPath();
    ctx.arc(screenX + half * 0.82, screenY - half * 0.55, half * 0.12, 0, Math.PI * 2);
    ctx.fill();
  },

  drawMinotaur(enemy, screenX, screenY) {
    const ctx = this.ctx;
    const half = enemy.size * 0.5;
    const now = typeof performance !== "undefined" ? performance.now() : Date.now();
    const moving = Math.hypot((enemy.x || 0) - (enemy.lastX ?? enemy.x ?? 0), (enemy.y || 0) - (enemy.lastY ?? enemy.y ?? 0));
    const walkPhase = Math.sin(now * 0.014 + (enemy.x || 0) * 0.035 + (enemy.y || 0) * 0.021) * Math.min(1, moving * 0.2 + 0.35);
    const chargeState = Math.max(enemy.chargeTimer || 0, enemy.chargeWindupTimer || 0);
    const chargeGlow = chargeState > 0 ? 0.22 : 0.08;
    const hornLower = Math.max(0, Math.min(1, (enemy.chargeWindupTimer || 0) / Math.max(0.01, this.config.enemy.minotaurWindup || 0.38)));
    const chargeLean = (enemy.chargeTimer || 0) > 0 ? 1 : hornLower;
    const armSwing = walkPhase * half * 0.18;
    const legSwing = walkPhase * half * 0.2;
    const hornDrop = hornLower * half * 0.18 + chargeLean * half * 0.08;
    const headY = screenY - half * (0.42 - chargeLean * 0.08);

    ctx.fillStyle = "rgba(0, 0, 0, 0.4)";
    ctx.beginPath();
    ctx.ellipse(screenX, screenY + half * 0.84, half * 1.08, half * 0.42, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = `rgba(255, 125, 82, ${chargeGlow})`;
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.ellipse(screenX, screenY + half * 0.18, half * 1.12, half * 0.8, 0, 0, Math.PI * 2);
    ctx.stroke();
    ctx.strokeStyle = "#5c311f";
    ctx.lineWidth = 5;
    ctx.lineCap = "round";
    ctx.beginPath();
    ctx.moveTo(screenX - half * 0.28, screenY + half * 0.54);
    ctx.lineTo(screenX - half * 0.38, screenY + half * 1.0 - legSwing);
    ctx.moveTo(screenX + half * 0.28, screenY + half * 0.54);
    ctx.lineTo(screenX + half * 0.38, screenY + half * 1.0 + legSwing);
    ctx.stroke();
    ctx.strokeStyle = "#74442b";
    ctx.lineWidth = 6;
    ctx.beginPath();
    ctx.moveTo(screenX - half * 0.5, screenY + half * 0.04);
    ctx.lineTo(screenX - half * 0.86, screenY + half * 0.34 + armSwing);
    ctx.moveTo(screenX + half * 0.5, screenY + half * 0.04);
    ctx.lineTo(screenX + half * 0.86, screenY + half * 0.34 - armSwing);
    ctx.stroke();
    ctx.fillStyle = "#6e4128";
    ctx.fillRect(screenX - half * 0.5, screenY - half * 0.12 + chargeLean * 2, half, half * 1.02);
    ctx.fillStyle = "#8a5738";
    ctx.beginPath();
    ctx.arc(screenX, headY, half * 0.44, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "#dcc59a";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(screenX - half * 0.15, headY - half * 0.38 + hornDrop);
    ctx.quadraticCurveTo(screenX - half * 0.6, headY - half * 0.7 + hornDrop, screenX - half * 0.72, headY - half * 0.05 + hornDrop);
    ctx.moveTo(screenX + half * 0.15, headY - half * 0.38 + hornDrop);
    ctx.quadraticCurveTo(screenX + half * 0.6, headY - half * 0.7 + hornDrop, screenX + half * 0.72, headY - half * 0.05 + hornDrop);
    ctx.stroke();
    ctx.fillStyle = "#36261d";
    ctx.fillRect(screenX - 5, headY - half * 0.06, 3, 3);
    ctx.fillRect(screenX + 2, headY - half * 0.06, 3, 3);
    ctx.strokeStyle = "#2a1a14";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(screenX - half * 0.12, headY + half * 0.18);
    ctx.lineTo(screenX + half * 0.12, headY + half * 0.18);
    ctx.stroke();
  },

  drawLeprechaunBoss(enemy, screenX, screenY) {
    const ctx = this.ctx;
    const half = enemy.size * 0.5;
    const enraged = enemy.phase === "enraged";
    ctx.fillStyle = "rgba(0, 0, 0, 0.4)";
    ctx.beginPath();
    ctx.ellipse(screenX, screenY + half * 0.82, half * 1.05, half * 0.38, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = enraged ? "#1f7c34" : "#2f9d43";
    ctx.fillRect(screenX - half * 0.38, screenY - half * 0.12, half * 0.76, half * 1.04);
    ctx.fillStyle = "#f3d2b3";
    ctx.beginPath();
    ctx.arc(screenX, screenY - half * 0.42, half * 0.34, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = "#d96c2b";
    ctx.beginPath();
    ctx.moveTo(screenX - half * 0.26, screenY - half * 0.18);
    ctx.lineTo(screenX + half * 0.26, screenY - half * 0.18);
    ctx.lineTo(screenX, screenY + half * 0.32);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = "#1e5f2c";
    ctx.beginPath();
    ctx.moveTo(screenX - half * 0.62, screenY - half * 0.56);
    ctx.lineTo(screenX, screenY - half * 1.02);
    ctx.lineTo(screenX + half * 0.62, screenY - half * 0.56);
    ctx.lineTo(screenX + half * 0.5, screenY - half * 0.18);
    ctx.lineTo(screenX - half * 0.5, screenY - half * 0.18);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = "#d4c35e";
    ctx.fillRect(screenX - half * 0.52, screenY - half * 0.18, half * 1.04, half * 0.12);
    ctx.fillStyle = "#2c2a1e";
    ctx.fillRect(screenX - half * 0.08, screenY - half * 0.2, half * 0.16, half * 0.16);
    ctx.fillStyle = "#f6f1d9";
    ctx.fillRect(screenX - half * 0.18, screenY - half * 0.48, half * 0.08, half * 0.06);
    ctx.fillRect(screenX + half * 0.1, screenY - half * 0.48, half * 0.08, half * 0.06);
    if (enraged) {
      ctx.strokeStyle = "rgba(167, 255, 121, 0.5)";
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.arc(screenX, screenY - half * 0.1, half * 1.15, 0, Math.PI * 2);
      ctx.stroke();
      ctx.fillStyle = "#5cda6b";
      ctx.fillRect(screenX - half * 0.9, screenY + half * 0.02, half * 0.3, half * 0.18);
      ctx.fillRect(screenX + half * 0.6, screenY + half * 0.02, half * 0.3, half * 0.18);
    }
  }
};
