export const CONFIG = {
  classes: {
    archer: {
      key: "archer",
      label: "Elvish Archer",
      usesRanged: true,
      baseLifeLeech: 0,
      baseMaxHealth: 95,
      baseDefenseFlat: 0,
      baseResistances: {},
      baseMoveSpeed: 176,
      baseAttackCooldown: 0.38,
      minAttackCooldown: 0.08,
      primaryDamageMin: 1.05,
      primaryDamageMax: 2.0,
      projectileSpeed: 360,
      passiveRegenPct: 0.01,
      levelHpGain: 6,
      levelWeaponDamagePct: 0.05,
      levelMoveSpeedGain: 2.5,
      levelAttackSpeedPct: 0.015
    },
    fighter: {
      key: "fighter",
      label: "Castle Warrior",
      usesRanged: false,
      combatStyle: "warrior",
      baseLifeLeech: 0.01,
      baseMaxHealth: 125,
      baseDefenseFlat: 2.5,
      baseResistances: {
        unholy: 0.24
      },
      baseMoveSpeed: 132,
      baseAttackCooldown: 0.46,
      minAttackCooldown: 0.16,
      primaryDamageMin: 2.2,
      primaryDamageMax: 4.1,
      projectileSpeed: 0,
      meleeRange: 42,
      meleeHitPadding: 10,
      meleeArcDeg: 95,
      passiveRegenPct: 0.02,
      levelHpGain: 10,
      levelWeaponDamagePct: 0.05,
      levelDefenseFlatGain: 0.35,
      levelLifeLeechGain: 0.002
    },
    necromancer: {
      key: "necromancer",
      label: "Reformed Necromancer",
      usesRanged: true,
      combatStyle: "necromancer",
      baseLifeLeech: 0,
      baseMaxHealth: 88,
      baseDefenseFlat: 0,
      baseResistances: {},
      baseMoveSpeed: 148,
      baseAttackCooldown: 0.08,
      minAttackCooldown: 0.08,
      primaryDamageMin: 0,
      primaryDamageMax: 0,
      projectileSpeed: 0,
      passiveRegenPct: 0.01,
      levelHpGain: 7,
      levelWeaponDamagePct: 0.03,
      levelControlPowerPct: 0.03,
      levelCharmTimeReductionPct: 0.015
    }
  },
  map: {
    tile: 32,
    width: 120,
    height: 90,
    exploreRadiusTiles: 4,
    defaultBiomeKey: "catacomb",
    biomeCycle: ["catacomb", "catacomb", "catacomb", "sewer"]
  },
  player: {
    maxHealth: 100,
    hpBarDuration: 1.25,
    lowHealthThreshold: 0.35,
    hitDamage: 16,
    enemyCollisionSize: 16,
    pickupRadius: 18,
    primaryDamage: 1,
    projectileSpeed: 360,
    baseMoveSpeed: 145,
    sprintMultiplier: 1.4,
    moveSpeedPerLevel: 6,
    baseFireCooldown: 0.30,
    fireCooldownReductionPerLevel: 0.01,
    minFireCooldown: 0.08,
    spriteFrame: 64,
    spriteRenderSize: 44,
    spriteFramesPerDir: 2,
    spriteDirections: 8,
    animationSpeed: 10
  },
  effects: {
    sprintParticleLife: 0.22,
    sprintParticleSpawnRate: 24,
    meleeSwingLife: 0.17
  },
  enemy: {
    maxCount: 120,
    activeCapBase: 30,
    activeCapPerFloor: 10,
    activeCapMax: 200,
    speedAtZeroTime: 0.58,
    speedRampPerSecond: 0.0019,
    speedCap: 1.3,
    spawnIntervalStart: 2.6,
    spawnIntervalMin: 0.55,
    spawnIntervalRamp: 0.009,
    levelSpeedBase: 0.56,
    levelSpeedPerLevel: 0.06,
    levelSpeedCap: 1.9,
    levelSpawnRateBase: 1.0,
    levelSpawnRatePerLevel: 0.10,
    levelSpawnRateCap: 2.4,
    levelDamageBase: 1.0,
    levelDamagePerLevel: 0.11,
    levelDamageCap: 2.8,
    levelHealthBase: 1.0,
    levelHealthPerLevel: 0.1,
    levelHealthCap: 3.2,
    levelDefenseBase: 1.0,
    levelDefensePerLevel: 0.07,
    levelDefenseCap: 2.2,
    spawnEdgeMarginTiles: 4,
    goblinBaseContactDamage: 6,
    goblinSpawnChance: 0.03,
    maxActiveGoblins: 2,
    mummySpawnChance: 0.08,
    mummyMinFloor: 4,
    maxActiveMummies: 2,
    prisonerSpawnChance: 0.1,
    prisonerMinFloor: 2,
    maxActivePrisoners: 4,
    prisonerHpMin: 12,
    prisonerHpMax: 18,
    prisonerSpeed: 58,
    prisonerDamageMin: 12,
    prisonerDamageMax: 18,
    prisonerAttackRangeTiles: 1.5,
    prisonerAttackArcDeg: 180,
    prisonerAttackCooldown: 0.65,
    prisonerWindup: 0.16,
    ratArcherSpawnChance: 0.06,
    ratArcherMinFloor: 3,
    maxActiveRatArchers: 5,
    ratArcherHpMin: 4,
    ratArcherHpMax: 8,
    ratArcherSpeed: 85,
    ratArcherDamageMin: 10,
    ratArcherDamageMax: 16,
    ratArcherContactDamageMin: 7,
    ratArcherContactDamageMax: 11,
    ratArcherPreferredRangeTiles: 7,
    ratArcherRetreatRangeTiles: 5,
    ratArcherAdvanceRangeTiles: 8.5,
    ratArcherHoldBandTiles: 1.1,
    ratArcherRepositionCommitTime: 1.35,
    ratArcherSpreadCount: 3,
    ratArcherSpreadDeg: 20,
    ratArcherWindup: 0.4,
    ratArcherShotInterval: 1.5,
    ratArcherBurstShots: 3,
    ratArcherBurstCooldown: 5,
    ratArcherProjectileSpeed: 360,
    ratArcherProjectileLife: 1.3,
    ratArcherDodgeRadiusTiles: 2,
    ratArcherDodgeDistanceTiles: 1.1,
    ratArcherDodgeDuration: 0.12,
    ratArcherDodgeCooldown: 2.5,
    ratArcherCoverSearchRadiusTiles: 6,
    skeletonWarriorSpawnChance: 0.25,
    skeletonWarriorMinFloor: 3,
    skeletonWarriorHpMin: 3,
    skeletonWarriorHpMax: 7,
    skeletonWarriorSpeed: 85,
    skeletonWarriorDamageMin: 10,
    skeletonWarriorDamageMax: 16,
    skeletonWarriorAttackRange: 42,
    skeletonWarriorAttackCooldown: 1.0,
    skeletonWarriorArrowIgnoreChance: 0.6,
    skeletonWarriorReviveChance: 0.2,
    skeletonWarriorBonePileLife: 5,
    skeletonWarriorReanimateWindup: 1.2,
    skeletonWarriorReviveHpPct: 0.35,
    skeletonWarriorBoneSlowPct: 0.5,
    goblinStrongGoldThreshold: 20,
    goblinFearRadius: 220,
    goblinFeedSearchRadiusTiles: 8,
    goblinFearBlend: 0.25,
    goblinWanderJitter: 1.8,
    goblinAggroPursuitRadius: 300,
    goblinEnrageRangeTiles: 1.5,
    armorStandCountFactor: 600,
    armorStandAnimatedChance: 0.35,
    armorWakeRadius: 260,
    mimicChestChance: 0.02,
    mimicChestChanceLevel5: 0.04,
    mimicMinFloor: 2,
    mimicChanceLevelThreshold: 5,
    mimicWakeRadiusTiles: 3,
    mimicTongueRangeTiles: 2,
    mimicTongueCooldown: 1.35,
    mimicTongueWindup: 0.18,
    mimicHpMin: 8,
    mimicHpMax: 12,
    mimicSpeed: 104,
    mimicDamageMin: 26,
    mimicDamageMax: 38,
    mimicArrowResistance: 0.45,
    mimicFireVulnerability: 1.75,
    ghostSpeedMin: 110,
    ghostSpeedMax: 150,
    ghostHpMin: 3,
    ghostHpMax: 7,
    ghostDamageMin: 10,
    ghostDamageMax: 16,
    ghostPreferredRangeTiles: 1.35,
    ghostRetreatRangeTiles: 0.8,
    ghostOrbitStrafeScale: 0.8,
    ghostOrbitApproachScale: 0.9,
    ghostOrbitSwapTimeMin: 1.4,
    ghostOrbitSwapTimeMax: 2.4,
    ghostOrbitSwapChance: 0.18,
    ghostSiphonRangeTiles: 1.55,
    ghostSiphonTickInterval: 0.22,
    ghostSiphonDps: 7.5,
    ghostSiphonHealPct: 0.4,
    ghostDiveIntervalMin: 1.8,
    ghostDiveIntervalMax: 3.4,
    ghostDiveDuration: 0.65,
    ghostDiveAttackRangeTiles: 0.95,
    goblinHpMin: 2,
    goblinHpMax: 5,
    goblinDamageMin: 5,
    goblinDamageMax: 9,
    mummyHpMin: 18,
    mummyHpMax: 28,
    mummySpeed: 54,
    mummyDamageMin: 12,
    mummyDamageMax: 18,
    mummyAuraRangeTiles: 1.8,
    mummyAuraDps: 8,
    armorHpMin: 14,
    armorHpMax: 24,
    armorSpeed: 72,
    armorDamageMin: 20,
    armorDamageMax: 32,
    minotaurHpMin: 80,
    minotaurHpMax: 110,
    minotaurSpeed: 88,
    minotaurDamageMin: 20,
    minotaurDamageMax: 30,
    minotaurChargeRangeTiles: 6.5,
    minotaurChargeSpeedMultiplier: 2.9,
    minotaurChargeTravelTiles: 7,
    minotaurChargeDuration: 0.6,
    minotaurChargeCooldown: 3.8,
    minotaurWindup: 0.38,
    minotaurChargePushDistanceTiles: 1.2,
    minotaurChargeContactDamageMultiplier: 1.3,
    minotaurStompRangeTiles: 1.8,
    minotaurStompCooldown: 2.2,
    minotaurRewardGoldMin: 110,
    minotaurRewardGoldMax: 150,
    necromancerHpMin: 36,
    necromancerHpMax: 48,
    necromancerSpeed: 76,
    necromancerBossHpMultiplier: 1.55,
    necromancerBossSpeedMultiplier: 1.22,
    necromancerDamageMin: 18,
    necromancerDamageMax: 28,
    necromancerPreferredRangeTiles: 5,
    necromancerRetreatRangeTiles: 3,
    necromancerCastCooldown: 2.5,
    necromancerProjectileSpeed: 230,
    necromancerProjectileLife: 2.8,
    necromancerProjectileSize: 12,
    necromancerProjectileDamage: 13,
    necromancerProjectileSpreadDeg: 16,
    necromancerSummonCooldown: 6.4,
    necromancerSummonCap: 4,
    necromancerSummonCount: 1,
    necromancerBossTeleportRangeTiles: 8,
    necromancerBossTeleportCooldown: 4.5,
    necromancerBossTeleportMinRangeTiles: 3.25,
    necromancerBossTeleportMaxRangeTiles: 4.75,
    necromancerBossTeleportHealthThreshold: 0.8,
    necromancerBossSummonCooldownMultiplier: 0.68,
    necromancerBossSummonCapBonus: 2,
    necromancerBossSummonCountBonus: 1,
    necromancerRewardGoldMin: 90,
    necromancerRewardGoldMax: 130,
    sonyaHpMin: 160,
    sonyaHpMax: 210,
    sonyaSpeed: 112,
    sonyaDamageMin: 20,
    sonyaDamageMax: 30,
    sonyaPreferredRangeTiles: 5.5,
    sonyaRetreatRangeTiles: 3.25,
    sonyaCastCooldown: 1.8,
    sonyaCastWindup: 0.42,
    sonyaFireballSpeed: 212,
    sonyaFireballLife: 2.8,
    sonyaFireballSize: 13,
    sonyaFireballDamage: 18,
    sonyaFireballSpreadDeg: 22,
    sonyaVolleyCount: 3,
    sonyaBlinkCooldown: 4.8,
    sonyaBlinkHealthThreshold: 0.6,
    sonyaFirePatchRadiusTiles: 1.1,
    sonyaFirePatchDuration: 3.6,
    sonyaFirePatchDps: 14,
    sonyaSpeechCooldownMin: 4.4,
    sonyaSpeechCooldownMax: 7.2,
    leprechaunFleeSpeed: 240,
    leprechaunIntroSpeed: 178,
    leprechaunRunToPotSpeed: 286,
    leprechaunEnragedSpeed: 152,
    leprechaunGoldDropTotal: 1000,
    leprechaunGoldPileMin: 10,
    leprechaunGoldPileMax: 35,
    leprechaunGoldDropCooldown: 0.1,
    leprechaunGoldDropMinDuration: 10,
    leprechaunIntroApproachTiles: 3,
    leprechaunTransformRangeTiles: 8,
    leprechaunTimerSeconds: 300,
    leprechaunPunchRangeTiles: 2.2,
    leprechaunPunchCooldown: 2.2,
    leprechaunPunchWindup: 0.32,
    leprechaunPunchDamageMin: 28,
    leprechaunPunchDamageMax: 42,
    leprechaunPunchKnockbackTiles: 20,
    leprechaunPunchKnockbackCooldown: 15,
    leprechaunPunchKnockbackDuration: 0.28,
    leprechaunCharmCooldown: 1.2,
    leprechaunCharmProjectileSpeed: 300,
    leprechaunCharmProjectileLife: 2.2,
    leprechaunCharmProjectileDamage: 18,
    leprechaunCharmVolleyCount: 5,
    leprechaunCharmSpreadDeg: 28,
    leprechaunHpMin: 260,
    leprechaunHpMax: 340,
    leprechaunDamageMin: 24,
    leprechaunDamageMax: 38,
    leprechaunRewardGoldMin: 280,
    leprechaunRewardGoldMax: 380,
    skeletonHpMin: 8,
    skeletonHpMax: 12,
    skeletonSpeed: 96,
    skeletonDamageMin: 8,
    skeletonDamageMax: 12,
    hpBarDuration: 0.9
  },
  drops: {
    life: 14,
    rateGold: 0.10,
    rateHealth: 0.05,
    healthRestorePct: 0.25,
    goldMin: 5,
    goldMax: 20,
    treasureBagBaseGold: 45,
    treasureBagBonusGold: 35
  },
  breakables: {
    spawnChance: 0.018,
    maxCount: 160,
    minDistanceFromPlayerTiles: 5,
    dropGoldRate: 0.04,
    dropHealthRate: 0.02,
    goldMin: 2,
    goldMax: 9
  },
  traps: {
    wall: {
      minCount: 5,
      maxCount: 12,
      sightRangeTiles: 8,
      detectRangeTiles: 12,
      detectForwardChance: 0.5,
      initialArmDelay: 5,
      resetMin: 10,
      resetMax: 30,
      projectileSpeed: 520,
      projectileLife: 1.6,
      projectileSize: 10
    }
  },
  progression: {
    baseXpToLevel: 30,
    xpLevelScaling: 1.35,
    xpRewardMultiplierByLevel: [
      1.0,
      1.04,
      1.08,
      1.13,
      1.18,
      1.24,
      1.31,
      1.39,
      1.5,
      1.64,
      1.76,
      1.88,
      2.0,
      2.12,
      2.24,
      2.36,
      2.48,
      2.6,
      2.72,
      2.84
    ],
    mapGrowthFactorByFloor: {
      2: 1.12,
      3: 1.1,
      4: 1.06
    },
    mapGrowthFactorDefault: 1.03,
    floorBossLevelMultiplier: 5,
    floorOneLeprechaunBossChance: 0.2
  },
  fireArrow: {
    cooldown: 2.0,
    speed: 330,
    life: 1.2,
    impactDamage: 3.2,
    baseBlastRadius: 46,
    blastRadiusPerLevel: 2.6,
    lingerDuration: 1.0,
    lingerDps: 3.6
  },
  necromancer: {
    controlRangeTiles: 10,
    charmDuration: 2.0,
    minCharmDuration: 0.5,
    beamWidth: 11,
    healTickSeconds: 0.2,
    healAmount: 3,
    healSelfCost: 1,
    baseControlCap: 2,
    followDistanceTiles: 2.2,
    leashDistanceTiles: 4.5,
    aggroRangeTiles: 6.5,
    petBuffPerRank: 0.15
  },
  deathBolt: {
    cooldown: 10,
    hpCostPct: 0.05,
    speed: 165,
    life: 1.6,
    impactRadiusTiles: 2,
    visualLife: 5,
    pulseInterval: 1
  },
  explodingDeath: {
    radiusTiles: 3
  },
  warriorRage: {
    duration: 10,
    cooldown: 20,
    maxCooldownReductionPct: 0.4,
    baseDamageBonus: 0.3,
    baseDamageBonusPerPoint: 0.14,
    victoryRushPerKillMinPct: 0.01,
    victoryRushPerKillMaxPct: 0.03,
    victoryRushPoolCapPct: 0.2,
    victoryRushHotDuration: 15
  },
  minimap: {
    width: 220,
    height: 165,
    margin: 14,
    yOffset: 78
  },
  hud: {
    sidebarWidth: 300,
    topHudHeight: 36
  },
  multiplayer: {
    spawnRatePerPlayer: 0.18,
    spawnRateCap: 1.45,
    activeCapPerPlayer: 0.22,
    activeCapCap: 1.65,
    speedPerPlayer: 0.05,
    speedCap: 1.18,
    damagePerPlayer: 0.06,
    damageCap: 1.24
  }
};
